### ISSUE TITLE
start.py not recognizing numbers

### ISSUE THREAD

**Issue by StjepanBM1** [ringwormGO-organization/ringwormGO-Standard-Code#1]
As I was developing number system in RGWS (ringwormGO Standard Code), I started start.py and guess what? Start.py can't recognize numbers! I wonder if anyone even tested Start.py, also it keeps doubling otp.printr command.

![Screenshot from 2022-01-29 09-40-03](https://user-images.githubusercontent.com/94230991/151654249-d15ddf6d-e3c7-4fe8-836c-e037186982da.png)

**Comment by Andrej123456789** [comment]
I need basic.py

**Comment by StjepanBM1** [comment]
from sys import*
        
        tokens = []
        
        def open_file(filename):
	        data = open(filename, "r").read()
	        return (data)
        
        def lex(filecontents):
	        tok = ""
	        state = 0
	        string = ""
	        expr = ""
	        n = ""
        
	        filecontents = list(filecontents)
	        for char in filecontents:
		        tok += char
		        if tok == " ":
			        if state == 0:
				        tok = ""
        
			        else:
				        tok = " "
        
		        elif tok == ")":
			        if state == 0:
				        tok = ""
			        else:
				        tok = ")"
        
		        elif tok == "(":
			        if state == 0:
				        tok = ""
			        else:
				        tok = "("
        
		        elif tok == ";":
			        if state == 0:
				        tok = ""
			        else:
				        tok = ";"
        
		        elif tok == "\n":
			        tok = ""
        
		        elif tok == "otp.printr" or tok == "OPT.PRINTR":
			        tokens.append("PRINTR")
			        tok = ""
        
		        elif tok == "0" or tok == "1" or tok == "2" or tok == "3" or tok == "4" or tok == "5" or tok == "6" or tok == "7" or tok == "8" or tok == "9":
			        expr += tok
			        tok = ""
        
		        elif tok == "+":
			        expr += tok
			        tok = ""
        
		        elif tok == "\"":
			        if state == 0:
				        state = 1
			        elif state == 1:
				        tokens.append("STRING:" + string)
				        string = ""
				        state = 0
				        tok = ""
        
		        elif state == 1:
			        string += tok
			        tok = ""
        
	        #print(tokens)
	        print(expr)
	        return tokens
        
        def parse(toks):
	        i = 0
	        while(i < len(toks)):
		        if toks[i] + " " + toks[i+1][0:6] == "PRINTR STRING":
			        print(toks[i+1][8:])
			        i+=2
        
        def run(filename):
	        data = open_file(filename)
	        toks = lex(data)
	        parse(toks)

**Comment by Andrej123456789** [comment]
I think now will work

**Comment by StjepanBM1** [comment]
Ok it works now
